# Generated by Django 4.0.3 on 2022-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa emisora')),
                ('issue', models.DateField()),
                ('credential', models.CharField(max_length=200, verbose_name='ID de la credencial')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-issue'],
            },
        ),
    ]
